---
title: "README"
author: "Cande Torres"
date: "4/27/2022"
output: html_document
---

# Links to Data Sources 

[OxCGRT](https://covidtracker.bsg.ox.ac.uk)
[PISA School Questionnaire](https://www.oecd.org/pisa/data/2018database/)
[World Development Indicators](https://databank.worldbank.org/source/world-development-indicators)
[UNESCO School Closing Monitoring](https://en.unesco.org/covid19/educationresponse#schoolclosures) 

For the exact data I used from the WDI check the data set WDI-combined.xlsx in the repository 

# Data Wrangling 
 
For data wrangling please check the Thesis_carefully an Thesis_carefully_2 rmds. The first, wrangles the OxCGRT data, merging it with the WDI and the UNESCO data sets. The second document processes the School Questionnaire data which is larger and heavier. 
 
# Data Analysis and Visualization 

For statistical modeling and data visualization please check the Thesis_analysis_1.0.Rmd in this repository. At the beginning of the document I merge the data sets I saved from the last two documents and I perform a last minute cleaning to merge them without any conflict. Data visualization is performed along the document. Subtitles for the different sections may help the reader interpret each chunck of code. Some partial data sets were created for the purpose of visualization so they do not exist in the repository but since they come from the original data set they can be easily reproduce running the whole rmd.  
 